# Generated by Django 3.0.5 on 2020-11-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.RenameModel(
            old_name='Employee',
            new_name='EmployeeModel',
        ),
        migrations.AlterModelTable(
            name='employeemodel',
            table='emploIntegerFieldyee',
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('fees', models.IntegerField(max_length=100)),
                ('courses', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.Course')),
            ],
            options={
                'db_table': 'course_details',
            },
        ),
    ]
