# Generated by Django 3.0.5 on 2020-11-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201122_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='fees',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='employeemodel',
            table='employee',
        ),
    ]
