# Generated by Django 3.0.5 on 2020-11-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201128_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetails',
            old_name='courses',
            new_name='coursesdssdf',
        ),
    ]
