# Generated by Django 3.0.5 on 2020-11-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201128_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetails',
            old_name='coursesdssdf',
            new_name='courses',
        ),
    ]
